[package]
name = "twitch-log-bot-ws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
indicatif = "0.17.5"
lazy_static = "1.4.0"
postgres = { version = "0.19.5", features = ["with-chrono-0_4"] }
regex = "1.8.4"
serde = "1.0.164"
serde_derive = "1.0.164"
serde_json = "1.0.99"
tungstenite = "0.19.0"
