version: '3'

services:
  db:
    container_name: db
    image: 'postgres:15'
    env_file: ./.envs/.dev
    ports:
      - '5432:5432'
    networks:
      - backend_network
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    restart: unless-stopped
