version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432