version: "3"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
      DB_POSTGRESDB_PASSWORD: dev
      MB_DB_PASS: dev
    ports:
      - "5432:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/database/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/database/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: unless-stopped
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      DATA_SOURCE_NAME: postgresql://dev:dev@postgres:5432/dev?sslmode=disable
    ports:
      - "9187:9187"
    networks:
      - backend_network
    depends_on:
      - postgres
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - backend_network
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - postgres_exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: dev
      GF_SECURITY_ADMIN_PASSWORD: dev
    ports:
      - "3000:3000"
    networks:
      - backend_network
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

  ubuntu_server:
    image: ubuntu:22.04
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    environment:
      SERVER_USERNAME: dev
      SERVER_PASSWORD: dev
    stdin_open: true
    tty: true
    ports:
      - "22:22"
    networks:
      - backend_network

  n8n:
    image: n8nio/n8n:latest
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: dev
      N8N_BASIC_AUTH_ACTIVE: true
      N8N_BASIC_AUTH_USER: dev
      N8N_BASIC_AUTH_PASSWORD: dev
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
    ports:
      - "5678:5678"
    networks:
      - backend_network
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: dev
      MB_DB_HOST: postgres
    ports:
      - "3001:3000"
    networks:
      - backend_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  backend_network:

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  n8n_data:
